version: '3'
  
services:
  db-traininarium:
    image: postgres:12
    container_name: db-traininarium
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
  
  app-traininarium:
    image: arutunyandmitry/traininarium-server:latest
    container_name: app-traininarium
    ports:
      - "${SERVER_HOST}:8000:8000"
    depends_on:
      - db-traininarium
    env_file:
      - .env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
