# Generated by Django 5.0.2 on 2024-06-12 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_group_kp', models.FloatField()),
                ('weight', models.FloatField()),
                ('physical_health', models.IntegerField()),
                ('mental_health', models.IntegerField()),
                ('is_difficult_to_walk', models.BooleanField(default=False)),
                ('is_blood_pressure', models.BooleanField(blank=True, null=True)),
                ('general_health', models.CharField(choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Very good', 'Very good'), ('Excellent', 'Excellent')])),
                ('sleep_time', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_dynamic_info',
                'ordering': ['created_at'],
                'get_latest_by': 'created_at',
                'indexes': [models.Index(fields=['created_at', 'user'], name='health_dyna_created_183e04_idx')],
            },
        ),
        migrations.CreateModel(
            name='StateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_heart_diseased', models.BooleanField(blank=True, null=True)),
                ('is_diabetic', models.BooleanField(blank=True, null=True)),
                ('is_diabetic_with_diseases', models.BooleanField(default=False)),
                ('diabetic_period', models.IntegerField(default=0)),
                ('is_kidney_diseased', models.BooleanField(blank=True, null=True)),
                ('is_kidney_disease_chronic', models.BooleanField(default=False)),
                ('is_cholesterol', models.BooleanField(blank=True, null=True)),
                ('is_stroked', models.BooleanField(blank=True, null=True)),
                ('height', models.IntegerField()),
                ('is_physical_activity', models.BooleanField(default=False)),
                ('is_smoker', models.BooleanField(default=False)),
                ('is_alcoholic', models.BooleanField(default=False)),
                ('is_asthmatic', models.BooleanField(default=False)),
                ('is_skin_cancer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_state_info',
                'indexes': [models.Index(fields=['user'], name='health_stat_user_id_b473bf_idx')],
            },
        ),
    ]
