# Generated by Django 5.0.2 on 2024-06-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('picture', models.ImageField(upload_to='')),
                ('body', models.CharField()),
            ],
            options={
                'ordering': ['created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
